### ISSUE TITLE
Domain and nameserver searches treat similar unicode chars (á ~ a) as the same

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-sql-provider#8] opened 2017-09-21 18:17 UTC
If a client search a domain or a nameserver by unicode name that includes a char with a similar unicode value (for example á ~ a) the db return all the coincidences for the char. If a client want to retrieve data from domain "exámple.com", the query returns all the coincidences that matches similar unicode chars (example.com, éxample.com, exámple.com, examplé.com, éxámplé.com), beside the fact that the ldh_name for these domains are different because á~a, é~e have differente unicode values. 

The query should search for the exact unicode char, at leats in domain unicode name search.

**Comment by pcarana** [comment] 2017-09-22 23:10
Debugging the issue, this seems to be at DB level. The implementation honours what the server sent (A-Label or U-Label), so that's good news.

The problem was reproduced at a MySQL 5.6 DB, and is behavior of the collation. An example can be seen here: [10.1.8.6 Examples of the Effect of Collation](https://dev.mysql.com/doc/refman/5.6/en/charset-collation-effect.html). Quoting some content of the link (just to have an idea):

> This is not a bug but rather a consequence of the sorting properties...

More information at [10.1.10.1 Unicode Character Sets](https://dev.mysql.com/doc/refman/5.6/en/charset-unicode-sets.html).

So, the database is the one with the problem, the comparisson of special characters (even when the DB supports UTF-8) doesn't works as we should normally expect, it isn't so restrictive to treat "á" as a different char than "a"; too bad for us, but that's how things are =|

**Comment by TheRedTrainer** [comment] 2017-10-10 22:53
Verified. This issue is related to DB management system, so it's not possible to validate it in the server.

**Comment by pcarana** [comment] 2017-11-09 18:02
Closing, fixed in Red Dog v1.2

**Closed as completed by pcarana** 2017-11-09 18:02 UTC
Labels: solved, verified
